### ISSUE TITLE
Workflow lack build script

### ISSUE THREAD

**Issue by kainstar** [atomicpages/docusaurus-plugin-react-docgen-typescript#12]
## Problem:
The on_push workflow don't have `npm run build` step, so the ci process only push `src` files to npm link v1.0.0, and the package can't be used normally.

## Solution:
You can add follow codes into your on_push.yml file before Release step, and publish the package again.

```
- name: Build
  run: npm run build
```

**Comment by atomicpages** [comment]
Released under `1.0.1`. Thanks for letting me know! 🙏
