### ISSUE TITLE
PropTable template from Readme not working

### ISSUE THREAD

**Issue by lukasbach** [atomicpages/docusaurus-plugin-react-docgen-typescript#3]
Hi, awesome project :) 

I've tried to use the template for the PropTable component from the readme, but encountered an issue: Because ``useDynamicImport`` returns null on the first render, and only seems to provide the props in the next render, the component crashes the React app. Adding

```
  if (!props) {
    return null;
  }
```

after the `useDynamicImport` call works. Maybe the readme should be updated or it should be mentioned that `useDynamicImport` may return null at the start :)

**Comment by atomicpages** [comment]
Nice catch, thanks for the contrib 🚀
